/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgressBar.java
 *
 * Created on 12.06.2012, 22:01:09
 */
package gui;

import peer2peer.FileTransfer;

/**
 *
 * @author Black
 */
public class ProgressBar extends javax.swing.JFrame {
    
    /** Creates new form ProgressBar */
    private FileTransfer trans;
    
    public ProgressBar(FileTransfer trans) {
        initComponents();
        this.trans = trans;
        pgbSize.setStringPainted(true);
    }

    public void setFileName(String name){
        lblName.setText(name);
    }
    
    public void setSpeed(String speed){
        lblSpeed.setText(speed);
    }
    
    public void setProgress(int value){
        pgbSize.setValue(value);
    }
    
    public void setMaxSize(int value){
        pgbSize.setMaximum(value/1000);
    }
    
    public void increaseValue(int value){
        pgbSize.setValue(pgbSize.getValue()+value/1000);
        double zahl1 = pgbSize.getValue();
        double zahl2 = pgbSize.getMaximum();
        double percent = zahl1/zahl2;
        pgbSize.setString((int)(percent*100) + "%  " + pgbSize.getValue() + "/" + pgbSize.getMaximum());
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgbSize = new javax.swing.JProgressBar();
        lblName = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("File Transfere");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblName.setText("jLabel1");

        lblSpeed.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbSize, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(lblName)
                    .addComponent(lblSpeed))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpeed)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        trans.close();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        trans.close();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JProgressBar pgbSize;
    // End of variables declaration//GEN-END:variables
}
